### ISSUE TITLE
During rsudp installation, an error related to berryconda3 appears. What should I do?

### ISSUE THREAD

**Issue by awy0809** [raspishake/rsudp#10]
Hello, I am trying to install rsudp anew, but I got the following error.

Installing berryconda3…
ERROR: File or directory already exists: /home/pi/berryconda3
If you want to update an existing installation, use the -u option.
Cleaning up temporary files…
Updating base conda environment…
/home/pi/rsudp/bin/unix-install.sh: line 155: conda: command not found
Source line already exists in /home/pi/.bashrc
Sourcing...
Activating conda…
/home/pi/rsudp/bin/unix-install.sh: line 194: conda: command not found
ERROR: Anaconda install failed. Check the error output and try again.

Even if I keep reinstalling, the same error is repeated. What should I do?

**Comment by osop-raspishake** [comment]
Please see forum. Closing.
