### ISSUE TITLE
pip3 install fails with mismatched versions

### ISSUE THREAD

**Issue by ashleyfraser** [raspishake/rsudp#38]
When Install rsudp using pip3, rsddp wants matplotlib <= 3.2.0 but obspy wants matplotlib > 3.2.0. This means I can have rsdup with matplotlib and it runs fine in real time but I can't write because obspy doesn't like my matplot libversion. 
Python version 3.8.10, ubuntu 20.04.4 LTS.

**Comment by iannesbitt** [comment]
Hi @ashleyfraser, please see Cappy's solution in #37. Not sure why matplotlib causes so many install errors, but the solution at least temporarily is to change the version pin from 3.2.0 to 3.1.2.

**Comment by iannesbitt** [comment]
This should be solved now, but feel free to reopen if it is not.
