### ISSUE TITLE
(OSX/Darwin) Install fails to find /opt/miniconda3 installations

### ISSUE THREAD

**Issue by iannesbitt** [raspishake/rsudp#48]
conda's MacOS/Darwin graphical installers put their installations in `/opt[ana/mini]conda3`. This evades the rsudp installer's detection and causes it to download and install an additional miniconda installation to `~/miniconda3`.

- rsudp installer must be able to find `/opt/[ana/mini]conda3` installs and work within their structure. 
- rsudp installer must respect that `zsh` is the preferred Darwin shell, rather than `bash`. Forcing `bash` may cause issues.
- rsudp installer should work on Darwin out of the box as it does for GNU and other *nix

We probably don't need to install to `/opt` on Darwin, as it is a protected directory and we want rsudp to be able to avoid permissions complications. (side note: I wonder why they install to `/opt` rather than the user directory...is it a security thing? I can't imagine it would make much difference in an attack, but it is very annoying to deal with...)

**Comment by dmitryint** [comment]
For this case we added the creation of symbolic links. This will require a `sudo` on run, but it works. It will also fail if there are two installations in the `/opt` and user folder `$HOME/$release`.
[Eurasian](https://github.com/raspishake/rsudp/releases/tag/2.0.0)
