### ISSUE TITLE
Certificate for fdsnws.raspberryshakedata.com is expired, causing inventory fetch to fail on startup.

### ISSUE THREAD

**Issue by Lallirafn** [raspishake/rsudp#52]
Certificate for fdsnws.raspberryshakedata.com is expired, causing inventory fetch to fail on startup. This messes up deconvolve (i think its called) and i get only counts instead of mm/sec on the graphs. 

Do you have contacts at raspberryshake to ask them to fix the letsencrypt config and renew the certs?

![image](https://user-images.githubusercontent.com/1114492/225766498-219bc27b-e11d-467b-80cd-c5a962a14293.png)
![image](https://user-images.githubusercontent.com/1114492/225767185-bb4d976e-5f65-49a1-a743-b2384f23fe33.png)

![image](https://user-images.githubusercontent.com/1114492/225767346-eb780a1a-ebee-48c1-930b-beefb2db63a7.png)

**Comment by Lallirafn** [comment]
when calling from a browser it sometimes correctly redirects to https://data.raspberryshake.org/fdsnws/station/1/query?network=AM&station=........................... maybe time to fix the url call in the source?

**Comment by Lallirafn** [comment]
confirmed. but when changed to data.raspberryshake.org this warning is displayed instead:
![image](https://user-images.githubusercontent.com/1114492/225772550-17e8bf4d-4923-44d4-b4b1-fbfdbf6f2cfe.png)

**Comment by iannesbitt** [comment]
It looks like the letsencrypt certificate for fdsnws.raspberryshakedata.com was renewed. Can you confirm this problem still exists?

**Comment by Lallirafn** [comment]
the certificate has been renewed so the original error is resolved, but the url is redirected to https://data.raspberryshake.org/fdsnws/station/1/query?network=AM&station=(REMOVED)&level=resp&nodata=404&format=xml where the dataformat for the XML is 1.2 and ObsPy throws a warning: ".....\miniconda3\envs\rsudp\lib\site-packages\obspy\io\stationxml\core.py:98: UserWarning: The StationXML file has version 1.2, ObsPy can read versions (1.0, 1.1). Proceed with caution."

**Comment by iannesbitt** [comment]
This is a message generated by Obspy, and it should be safe to ignore. Per obspy/obspy#3153, a fix for this has been merged into their maintenance branch and should be released soon. The schema difference should not affect rsudp's performance.

**Comment by dmitryint** [comment]
We will close this issue but feel free to re-open it if you think that we missed something.
