### ISSUE TITLE
Dependecies for obspy 1.4.0 fail

### ISSUE THREAD

**Issue by MLSalmon** [raspishake/rsudp#60]
Obspy 1.4.0 now requires matplotlib 3.3 and python 3.8 there seems to be more and more dependencies going out of date for this software. 
You can install if you limit obspy<1.4 in setup.py

**Comment by dmitryint** [comment]
Hello, thanks for the feedback. We will try to update the dependencies to more recent versions for the project if I have enough time for this and it is possible. Obspy no longer supports the features we use.

**Comment by dmitryint** [comment]
https://github.com/raspishake/rsudp/pull/66

**Comment by dmitryint** [comment]
[Eurasian](https://github.com/raspishake/rsudp/releases/tag/2.0.0)
