### ISSUE TITLE
Feature Request - Additional Twitter Hashtags

### ISSUE THREAD

**Issue by kipdee** [raspishake/rsudp#9]
Hi,

Suggestion, on the twitter module, the ability to add other hashtags from the configuration file.  For example In my case I would add #earthquake #sismo #USVIWX #USVI

(#RaspberryShake station AM.R7078 - region: Virgin Islands) Event detected at 2020-10-16 05:52:08.20 UTC - live feed 
 https://raspberryshake.net/stationview/#?net=AM&sta=R7078 <inserted here>

(#RaspberryShake station AM.R7078 - region: Virgin Islands) Image of event detected at 2020-10-16 05:52:08.20 UTC <inserted here>

Thanks

**Comment by iannesbitt** [comment]
Hi @kipdee, I think it would be reasonable to add this to the config file. It might take a little while though, since I don't work on this full time anymore.

**Comment by iannesbitt** [comment]
The [extra-text](https://github.com/raspishake/rsudp/tree/extra-text) branch will contain this feature until it can be fully tested.

**Comment by kipdee** [comment]
Hi Ian,

  Its Hector,  I'm running it on @QuakeUsvi and its working.  If I see any issues I'll let you know

Thanks

This was a stump test :) 
![image](https://user-images.githubusercontent.com/61353444/104082022-21c9f900-5209-11eb-88d7-1572dd41867b.png)

**Comment by iannesbitt** [comment]
Great to hear. This feature is now merged to master.
Documentation for this feature can be found at https://raspishake.github.io/rsudp/settings.html#tweets-twitter-notification-module
